import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from 'next/link';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Boston Dodgeball League",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div>
          <header className="bg-blue-500 text-white p-4 text-center">
            <h1>Boston Dodgeball League</h1>
            <nav>
              <ul className="flex justify-center space-x-4">
                <li><Link href="/">About</Link></li>
                <li><Link href="/events">Events</Link></li>
                <li><Link href="/rules">Rules and Player Forms</Link></li>
              </ul>
            </nav>
          </header>
          {children}
          <footer className="bg-yellow-400 text-black p-4 text-center fixed bottom-0 w-full">
            <ul className="flex justify-center space-x-4">
              <li><a href="https://bostondodgeballleague.buyproforma.com/">Merch</a></li>
              <li><a href="https://www.instagram.com/boston.dodgeball.league/">Instagram</a></li>
              <li><a href="https://www.youtube.com/@BostonDodgeballLeague">YouTube</a></li>
              <li><a href="https://www.facebook.com/profile.php?id=61558561226354">Facebook</a></li>
            </ul>
          </footer>
        </div>
      </body>
    </html>
  );
}
